version: 2.1
orbs:
  node: circleci/node@1.1.6
  slack: circleci/slack@4.4.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test
            - run: npm run lint
            - slack/notify:
                channel: full-stuck
                event: fail
                template: basic_fail_1
            - slack/notify:
                channel: full-stuck
                event: pass
                template: basic_success_1
            - slack/notify:
                channel: full-stuck
                event: pass
                template: success_tagged_deploy_1
workflows:
    build-and-test:
      jobs:
        - build-and-test